version: '3'
services:
  consul:
    container_name: consul
    image: consul
    ports:
      - "8300"
      - "8400"
      - "8500"
    restart: always
  registrator:
    container_name: registrator
    image: gliderlabs/registrator:master
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    command: consul://consul:8500
    restart: always
    depends_on:
      - consul
  php:
    image: phpapp
    volumes:
      - ./:/app
    working_dir: /app
  php-food-service:
    image: php-foodservice-app
    volumes:
      - ./php-food/:/app
    working_dir: /app
  php-culture-service:
    image: php-cultureservice-app
    volumes:
      - ./php-culture/:/app
    working_dir: /app
  web:
    image: nginxserver
    volumes:
      - ./:/app
    depends_on:
      - php
    ports:
      - 80:80
  web2:
    image: nginxserver-food-service
    volumes:
      - ./:/app
    depends_on:
      - php-food-service
    ports:
      - 8081:80
  web3:
    image: nginxserver-culture-service
    volumes:
      - ./:/app
    depends_on:
      - php-culture-service
    ports:
      - 8082:80
  mysql:
    image: mysql:5.7.21
    volumes:
      - ./:/app
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=world
      - MYSQL_ROOT_PASSWORD=root
    working_dir: /app
volumes:
  dbdata:
